# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['entry.py'],
             pathex=([
             'K:\\PROGRAMMING\\mippy',
             'C:/Users/rtfm/AppData/Local/Programs/Python/Python37/Lib/site-packages',
             'C:/Users/rtfm/AppData/Local/Programs/Python/Python37/Lib/site-packages/scipy/.libs',
             'C:/Users/rtfm/AppData/Local/Programs/Python/Python37/Lib/site-packages/numpy/.libs'
             ]),
#             binaries=([
#              ( 'C:/Users/rtfm/AppData/Local/Programs/Python/Python37/Lib/site-packages/scipy/.libs/*', 'scipy/.libs' ),
#              ( 'C:/Users/rtfm/AppData/Local/Programs/Python/Python37/Lib/site-packages/numpy/.libs/*', 'numpy/.libs' )
#             ]),
             datas=([
              ('mippy/resources/*', 'mippy/resources'),
              ('mippy/luts/*','mippy/luts'),
              ('mippy/mviewer/*','mippy/mviewer')
             ]),
             hiddenimports=([
              'mippy',
              'mippy.mviewer',
              'mippy.fileio',
              'mippy.html',
              'mippy.improcess',
              'mippy.launcher',
              'mippy.math',
              'mippy.misc',
              'mippy.mlogging',
              'mippy.splash',
              'mippy.threading',
              'mippy.viewing',
              'mippy.mdicom',
              'mippy.mdicom.anon',
              'mippy.mdicom.io',
              'mippy.mdicom.mrenhanced',
              'mippy.mdicom.mrspectroscopy',
              'mippy.mdicom.pixel',
              'mippy.mdicom.reading',
              'mippy.mdicom.siemens',
              'mippy.mdicom.xml',
              'mippy.mri',
              'PIL',
              'nibabel',
              'nibabel.nicom',
              'nibabel.nicom.csareader',
              'tinydb',
              'requests',
              'tkinterhtml',
              'numpy',
              'scipy',
              'scipy.stats',
              'scipy.special',
              'scipy.linalg',
              'scipy.ndimage',
              'pydicom',
              'markdown2']),
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=True,
             win_private_assemblies=True,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='mippy',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='mippy')
